version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=nq£Oi#YyT:!Vq
      - POSTGRES_DB=typebot_config
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - typebot_network

  typebot:
    image: elestio/typebot-builder:latest
    container_name: typebot
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://docker_admin:tlqFHxYysV8MV28jK3c9P0n7r8OYtCXd@postgres:5432/typebot_config
      - ENCRYPTION_SECRET=4UBkOGpErjlaqKw2a5TNbOaHppFylXAx
      - NEXTAUTH_URL=http://localhost:3000
      - NEXT_PUBLIC_VIEWER_URL=http://app.localhost:3000
    networks:
      - typebot_network
    
  api:
    container_name: whataspp_api
    image: atendai/evolution-api
    build: .
    restart: always
    ports:
      - 8080:8080
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store
    networks:
      - typebot_network
    env_file:
      - ./Docker/.env
    command: ['node', './dist/src/main.js']
    expose:
      - 8080
      
networks:
  typebot_network:

volumes:
  postgres_data:
  evolution_instances:
  evolution_store: